### ISSUE TITLE
Try HPAs again with Clowder+app-interface

### ISSUE THREAD

**Issue by infinitewarp** [cloudigrade/cloudigrade#1207]
## Summary

As a cloudigrade sysop, I want autoscaling deployments so that we use only as much resources as we need.

Recent additions to Clowder indicate that working HPAs may finally be available. [We've been told](https://docs.google.com/document/d/1cqjGY7tJ7FbTpV6jLDi2EXnV2LM9rmXZd0tl4EdLPvw/edit):

> The HPA support was recently added. Pete said we should just be able to uncomment https://github.com/cloudigrade/cloudigrade/blob/master/deployment/clowdapp.yaml#L1170-L1204 and add a boolean to enable it

and an example of the extra setting required to enable:

```
   deployments:
    - name: metrics
      #
      # Component cloudigrade-metrics deployment:
      #
      minReplicas: ${{CELERY_METRICS_REPLICA_COUNT}}
      revisionHistoryLimit: 10
      autoscaler:
        externalHPA: true
```

## Acceptance Criteria

- [x] Verify default replica counts match our defined minimums.
- [x] Verify that putting load on one of the deployments results in more replicas/pods.
- [x] Verify that counts scale down after load stops.
- [x] Sanity-check our min and max values

## Assumptions and Questions

- How do we want to exercise load?
  - Maybe use the synthetic data API to generate a lot of activity in the workers
  - Maybe use some HTTP stress test against the API for more api pods
- If we encounter problems, please reach out to Pete Savage and/or Ben Turner.
- If this is successful, discuss and close https://github.com/cloudigrade/cloudigrade/issues/1066
