### ISSUE TITLE
Azure: attach image to an instance for inspection

### ISSUE THREAD

**Issue by katherine-black** [cloudigrade/cloudigrade#490]
In GitLab by @infinitewarp on Sep 4, 2018, 11:27

## Summary

For Azure, attach image to an instance for "inspection". This is to find an analog for our implementation around AWS's ECS process used for houndigrade. This does not actually need to inspect the contents of the attached volume. We just need to attach and verify that we can see the filesystem inside it.

This is somewhat dependent on being able to "get into the account". See: https://gitlab.com/cloudigrade/cloudigrade/issues/480 

This is DIRECTLY dependent on https://gitlab.com/cloudigrade/cloudigrade/issues/483 (copy or mount image from customer)

Output: A rudimentary script to prove out this investigation using the Azure CLI or equivalent Python library.

See also: https://redhatmbu.aha.io/epics/METER-E-39

**Comment by katherine-black** [comment]
In GitLab by @werwty on Sep 12, 2018, 16:53

unassigned @werwty

**Comment by katherine-black** [comment]
In GitLab by @infinitewarp on Sep 19, 2018, 16:43

removed milestone

**Comment by katherine-black** [comment]
In GitLab by @werwty on Oct 19, 2018, 24:04

Azure has a couple of different storage solutions we might use to mount and inspect the VHD we copied over from the client. But these storage solutions work differently with each azure tool (for example we can't straight up mount the blob storage with in an Azure Container Instance)

Azure's storage solutions are:

1. Blob
2. File (this is basically more structured blob storage)
3. Disk (this is a disk created from the VHD)

Here is an guide to the difference between these: https://docs.microsoft.com/en-us/azure/storage/common/storage-decide-blobs-files-disks
If we use Blob or File, we get a bunch of .vhd files, that we have to mount in order to inspect. 

As a note, Azure says: `[Use blob storage when] you want to be able to access application data from anywhere.` This is a lie. Most of the Azure Tools we look at does not support accessing blobs.


## Azure-Container-Instance

https://docs.microsoft.com/en-us/azure/container-instances/
https://docs.microsoft.com/en-us/cli/azure/container

This is Azure's lightweight container tool. The only storage option it supports is mounting an Azure Fileshare (and git, and secret, but we can't really use those).

We can create a container with the fileshare mounted using

```
az container create \
    --resource-group MC_eastus-group_cloudigrade-cluster_eastus \
    --name test1 \
    --image werwty/docker-nginx-libguestfs \
    --azure-file-volume-account-name cloudigradeaksstorage \
    --azure-file-volume-account-key \
    --azure-file-volume-share-name fileshare \
    --azure-file-volume-mount-path /mnt/cloudigrade/
```

We can then see the .vhd files on the container at`/mnt/cloudigrade/files/`. 
But, these .vhd files cannot be mounted in the container without more permission than we can get from ACI. Specifically we need the `cap_sys_admin` capability in order to mount things in a container. Unfortunately ACI does not give us a way to connect to the underlying Docker API, or run priviledged container [0]


## Azure-Kubernetes-Service

https://docs.microsoft.com/en-us/azure/aks/

Spinning up one of these gives us a kubernetes cluster. AKS allows us to mount disks and fileshares, but not blobs.

There are some problems with mounting disks: 
1. Azure only allows 4 volumes to be mounted to a cluster at once. We would have a batch size of 4.
2. Azure mounts the disks at /dev/sd{c-f} but we are not told where it mounts a specific disk. We can assume they'll be mounted sequentually, but this is assuming Azure behavior remains sane. 
3. Creating a disk from a Blob requires a `disk-size` argument. If this is not provided Azure defaults to 1024GB per disk. 



An alternate solution is to mount a fileshare, and then mount each vhd in that fileshare individually for inspection.
As a POC, I've done this with a privileged pod, we can narrow down the pod capabilities in the future. 


1. Create AKS group in Azure
2. Get the credentials locally, so we can authenticate with kubectl

    ` az aks get-credentials --resource-group eastus-group --name houndigrade-cluster`
    
    To view the kubernetes cluster run: `az aks browse --resource-group eastus-group --name houndigrade-cluster`

3. Create a kubernetes secret so kubernetes has access to our storage account:
`kubectl create secret generic azure-secret --from-literal=azurestorageaccountname=storageaccount4 --from-literal=azurestorageaccountkey=`
4. Create a pod using this yaml:
```
apiVersion: v1
kind: Pod
metadata:
  name: cloudipod
spec:
  containers:
  - image: fedora:latest
    name: cloudipod
    command: ["/bin/bash", "-ec", "while :; do echo '.'; sleep 5 ; done"]
    securityContext:
      privileged: true
      allowPrivilegeEscalation: true
    resources:
      requests:
        cpu: 200m
        memory: 256Mi
      limits:
        cpu: 250m
        memory: 256Mi
    volumeMounts:
      - name: azure
        mountPath: /mnt/azure
  volumes:
  - name: azure
    azureFile:
      secretName: azure-secret
      shareName: fileshare
      readOnly: false
```
5. In the pod itself we can run the following commands to see the internal vhd disk structure:

![image](/uploads/85b4c1677dc2f72922737b215fa6de17/image.png)

[0] https://docs.microsoft.com/en-us/azure/container-instances/container-instances-troubleshooting#cannot-connect-to-underlying-docker-api-or-run-privileged-containers

Here is a jupyter notebook with notes, and with the script to copy a source blob to a fileshare. 
[484-attach-image-to-instance-Copy1.ipynb](/uploads/993f6cb7e930cff6fb8889fde530858e/484-attach-image-to-instance-Copy1.ipynb)
