### ISSUE TITLE
Azure: start an instance with a dynamic entry point

### ISSUE THREAD

**Issue by katherine-black** [cloudigrade/cloudigrade#492]
In GitLab by @infinitewarp on Sep 4, 2018, 15:44

## Summary

For Azure, start an instance of a known image definition where we are able to give that instance a dynamic one-time CLI command (like Docker's "entry point"). This is to find an analog for our implementation around AWS's ECS process used for houndigrade in which we give a "task definition" that includes the houndigrade CLI script and arguments. 

For sake of investigation, a simple `echo "hello world"` command is good enough. As long as can give a dynamic value at start time, we should be OK.

Ideally, the instance should be able to shut itself down and clean up after the "entry point" process terminates. If this is not possible, please take note for future investigation.

This is somewhat dependent on being able to "get into the account". See: https://gitlab.com/cloudigrade/cloudigrade/issues/480 Also dependent on https://gitlab.com/cloudigrade/cloudigrade/issues/484 (attach image)

Output: A rudimentary script to prove out this investigation using the Azure CLI or equivalent Python library.

See also: https://redhatmbu.aha.io/epics/METER-E-39

**Comment by katherine-black** [comment]
In GitLab by @infinitewarp on Sep 19, 2018, 16:43

removed milestone

**Comment by katherine-black** [comment]
In GitLab by @katherine-black on Nov 12, 2018, 08:47

## Running Custom Commands

This builds on top of the work Bihan did in https://gitlab.com/cloudigrade/cloudigrade/issues/484. What I did is take the Pod definition that She created, and turn it into a Job definition. This allows us to run one off jobs for individual inspections, without having to deal with the Pod objects that generally want to stay running, an example of this definition is included below.

```
apiVersion: batch/v1
kind: Job
metadata:
  name: cloudijob
spec:
  parallelism: 1
  completions: 1
  template:
    metadata:
      name: cloudijob
    spec:
      restartPolicy: OnFailure
      containers:
      - image: registry.gitlab.com/cloudigrade/houndigrade:0.1.3
        name: cloudipod
        args: ["--help"]
        securityContext:
          privileged: true
          allowPrivilegeEscalation: true
        resources:
          requests:
            cpu: 200m
            memory: 256Mi
          limits:
            cpu: 250m
            memory: 256Mi
        volumeMounts:
          - name: azure
            mountPath: /mnt/azure
      volumes:
      - name: azure
        azureFile:
          secretName: azure-secret
          shareName: fileshare
          readOnly: false
```

`args: ["--help"]` Can be replaced with an appropriate definition for inspection, e.g. `args: ["-c", "azure", "-t", "vm-potato", "/dev/azure/potato.vhd"]`

## Misc notes

Here are some findings about Azure that may help with implementation later down the line. It seems like Azure VMs can be created from two sources, either Images, or a Disk. It seems to me that Images are.. pointless? While an image can not be deleted when there is a VM existant that's created from it, the source of the image _can_ be deleted. Disks on the other hand, seem to have a 1:1 relationship between the disk and the VM, which means one would have to copy the disk to create more vms. tl;dr? It seems like we can not trust images, my opinion is that if we want to inspect vms, we have to inspect every single one. This likely means going to every vm, going to the disk, making a snapshot, and going from there. This appears rather inefficient, and we'll need to think about how we'll scale this process.
